[package]
name = "radix-leptos-slot"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
leptos_dom.workspace = true
radix-leptos-compose-refs.workspace = true
leptos-node-ref.workspace = true
web-sys.workspace = true